export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAILURE = 'login_failure'
export const LOGIN_LOADER = 'login_loader'
export const RESET_STATE = 'reset_state'
export const SET_TOKEN = 'set_token'
export const RESET_TOKEN = 'reset_token'