const en = {
    SIGN_UP: 'SIGN UP',
    ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
    SIGN_IN: 'Sign In',    
    LOGIN: 'LOGIN',
    SIGN_UP_TEXT: 'Sign Up',
    NEED_AN_ACCOUNT: 'Need an account?',    
    ENTER_YOUR_EMAIL: 'Enter your email',
    ENTER_YOUR_NAME: 'Enter your name',
    ENTER_YOUR_PASSWORD: 'Enter your password',
    CONFIRM_YOUR_PASSWORD: 'Confirm your password',    
    SIGNIN_NAVIGATION: 'signin',   
    SIGNUP_NAVIGATION: 'signup',    
    BOTTOM_NAVIGATION: 'bottomNavigator',
    EXPOLREBOOK_NAVIGATION: 'exploreBook',
    MYBOOK_NAVIGATION: 'myBook',
    EXPLORE_BOOKS: 'Explore Books',
    MY_BOOKS: 'My Books',
    ADD_TO_COLLECTION: 'ADD TO COLLECTION',
    USER_ALREADY_EXIST: 'User already exist',
    PASSWORD: 'Password does not match',
    ENTER_VALID_EMAIL: 'Enter valid email',
    PASSWORD_VALIDATION: 'Password must contain 8 characters',
    USER_DOES_NOT_EXIST: 'User does not exist',
    SUCCESSFULLY_ADDED: 'Successfully Added',
    LOGOUT_MESSAGE: 'Do you want to logout?',
    LOGOUT: 'Logout',
    CANCEL: 'Cancel',
    OK: 'OK',
    LOGOUT_NAVIGATION: 'logout',
    TODO: 'ToDo',
    TODO_NAVIGATION: 'todo'    
}

export default en;
